version: '3.8'
services:
  app:
    build: .
    image: smart-hostel:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      # Set these in a .env file or your environment for real use
      - JWT_SECRET=${JWT_SECRET:-dev-secret}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
      - MAIL_FROM=${MAIL_FROM}
    volumes:
      - ./uploads:/app/uploads
      - ./server/db.sqlite:/app/server/db.sqlite
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/api/health"]
      interval: 20s
      timeout: 5s
      retries: 5
